name: Build and push Docker containers

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:

jobs:
  docker:
    name: "Build Docker containers"  
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          file: docker/Dockerfile.env
          tags: firedrakeproject/firedrake-env:latest